import { useState } from 'react';
import { Camera as CameraIcon, Crosshair, Expand, EyeOff, LocateFixed, Maximize2, Pause, Play, ScanLine, Signal, Users } from 'lucide-react';
import { useSentinel } from '@/hooks/use-sentinel';
import { PageIntro, Panel, ScenarioControls } from '@/components/sentinel-shell';

export default function Cameras() {
  const { state } = useSentinel();
  const [selected, setSelected] = useState('cam-01');
  const [paused, setPaused] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const camera = state.cameras.find((item) => item.id === selected) ?? state.cameras[0];
  const detections = [
    { label: 'Anonymous tracks', Icon: Users, value: `${camera.peopleDetected} active`, tone: 'text-secondary' },
    { label: 'Trajectory clusters', Icon: LocateFixed, value: `${camera.density > 55 ? 8 : 4} groups`, tone: 'text-primary' },
    { label: 'Occlusion state', Icon: EyeOff, value: camera.density > 75 ? 'Elevated' : 'Nominal', tone: camera.density > 75 ? 'text-destructive' : 'text-secondary' },
    { label: 'Signal integrity', Icon: Signal, value: camera.online ? '99.7% packet health' : 'No signal', tone: camera.online ? 'text-secondary' : 'text-destructive' },
  ];
  return <div className="enter-rise">
    <PageIntro eyebrow="02 / COMPUTER VISION" title="Camera Analysis" description="Inspect anonymous tracks, directional flow, and edge inference output from the three venue feeds." action={<div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center border border-primary/35 bg-primary/10 text-primary"><CameraIcon size={14} /></span><span className="data-mono text-[9px] text-muted-foreground">3 FEEDS · 2.1M TRACKS / HR</span></div>} />
    <ScenarioControls />
    <div className="mb-5 grid gap-3 md:grid-cols-3">{state.cameras.map((item) => <button key={item.id} onClick={() => setSelected(item.id)} className={`panel flex items-center gap-3 p-3 text-left transition-colors ${selected === item.id ? 'border-primary/70 bg-primary/[.06]' : 'hover:border-muted-foreground/45'}`} data-testid={`button-select-camera-${item.id}`}><div className={`grid h-9 w-9 place-items-center border ${item.online ? 'border-secondary/35 bg-secondary/10 text-secondary' : 'border-destructive/35 bg-destructive/10 text-destructive'}`}><CameraIcon size={16} /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2 text-[11px] font-semibold">{item.name}<span className={`h-1.5 w-1.5 rounded-full ${item.online ? 'bg-secondary' : 'bg-destructive'}`} /></div><div className="data-mono mt-1 truncate text-[9px] text-muted-foreground">{item.zone} · {item.fps} FPS</div></div><div className="data-mono text-[17px] text-primary">{item.density}<span className="ml-0.5 text-[8px] text-muted-foreground">%</span></div></button>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1.55fr_1fr]">
      <Panel title={`${camera.name} · ${camera.zone}`} eyebrow={`FEED ${camera.id.toUpperCase()} / ANONYMOUS MODE`} action={<div className="flex items-center gap-3"><span className="flex items-center gap-1 data-mono text-[9px] text-secondary"><span className="status-pulse h-1.5 w-1.5 rounded-full bg-secondary" /> LIVE</span><Maximize2 size={14} className="text-muted-foreground" /></div>}>
        <div className={`scanline relative overflow-hidden bg-[#0b151f] ${expanded ? 'h-[480px]' : 'h-[390px]'}`}>
          <div className="absolute inset-0 opacity-45" style={{ backgroundImage: 'linear-gradient(110deg, transparent 30%, rgba(65,180,185,.12) 30.4%, transparent 31%), linear-gradient(90deg, rgba(47,67,82,.45) 1px, transparent 1px), linear-gradient(rgba(47,67,82,.45) 1px, transparent 1px)', backgroundSize: '100% 100%, 42px 42px, 42px 42px' }} />
          <div className="absolute left-[18%] top-[14%] h-[64%] w-[64%] border border-secondary/30"><div className="absolute left-[12%] top-[14%] h-[72%] w-[34%] border border-dashed border-primary/25" /><div className="absolute right-[8%] top-[28%] h-[48%] w-[30%] border border-dashed border-primary/25" /></div>
          {[...Array(16)].map((_, i) => <div key={i} className="absolute h-3 w-2 border border-secondary/70 bg-secondary/15" style={{ left: `${18 + (i * 19) % 61}%`, top: `${24 + (i * 31) % 48}%`, transform: `scale(${.7 + (i % 3) * .2})` }}><span className="absolute -left-1 -top-2 h-1 w-1 rounded-full bg-secondary" /></div>)}
          <div className="absolute left-[44%] top-[45%] h-14 w-20 -translate-x-1/2 -translate-y-1/2 border border-primary/70 bg-primary/5"><div className="absolute -top-4 left-0 data-mono text-[8px] text-primary">TRACK_0084 · 0.94</div><Crosshair size={13} className="absolute -left-1 -top-1 text-primary" /></div>
          <div className="absolute left-3 top-3 flex items-center gap-2 border border-border bg-background/80 px-2 py-1.5 data-mono text-[8px] text-muted-foreground"><ScanLine size={12} className="text-secondary" /> INFERENCE OVERLAY · ON {paused && '· PAUSED'}</div>
          <div className="absolute bottom-3 left-3 right-3 flex items-end justify-between"><div><div className="data-mono text-[9px] text-foreground">{camera.resolution}</div><div className="data-mono mt-1 text-[8px] text-muted-foreground">{camera.processing} · PRIVACY MASK ACTIVE</div></div><div className="flex gap-1"><button onClick={() => setPaused((value) => !value)} className="grid h-7 w-7 place-items-center border border-border bg-background/80 text-muted-foreground hover:text-foreground" aria-label={paused ? 'Resume feed' : 'Pause feed'} data-testid="button-pause-camera">{paused ? <Play size={12} /> : <Pause size={12} />}</button><button onClick={() => setExpanded((value) => !value)} className="grid h-7 w-7 place-items-center border border-border bg-background/80 text-muted-foreground hover:text-foreground" aria-label={expanded ? 'Shrink feed' : 'Expand feed'} data-testid="button-expand-camera"><Expand size={12} /></button></div></div>
        </div>
      </Panel>
      <Panel title="Feed metrics" eyebrow="CURRENT WINDOW">
        <div className="grid grid-cols-2 gap-px bg-border">{[['People detected', camera.peopleDetected, 'tracks'], ['Density', `${camera.density}%`, 'of field'], ['Frame rate', camera.fps, 'FPS'], ['Latency', camera.online ? '38' : '—', 'ms']].map(([label, value, unit]) => <div className="bg-card p-4" key={String(label)}><div className="data-mono text-[9px] uppercase tracking-[.12em] text-muted-foreground">{label}</div><div className="mt-2 data-mono text-[23px] text-foreground">{value}</div><div className="data-mono mt-1 text-[9px] text-muted-foreground">{unit}</div></div>)}</div>
        <div className="border-t border-border p-4"><div className="mb-3 flex items-center justify-between"><span className="text-[11px] font-semibold">Density heatmap</span><span className="data-mono text-[9px] text-primary">LIVE / 5s</span></div><div className="relative h-[104px] overflow-hidden border border-border bg-[#111c27]"><div className="absolute inset-0 grid grid-cols-8 grid-rows-4 gap-1 p-2 opacity-80">{[...Array(32)].map((_, i) => <span key={i} className={`rounded-[1px] ${i % 7 === 0 || (camera.density > 70 && i % 5 === 0) ? 'bg-destructive/85' : i % 3 === 0 ? 'bg-primary/55' : 'bg-secondary/20'}`} />)}</div><div className="absolute bottom-2 left-2 right-2 flex justify-between data-mono text-[8px] text-muted-foreground"><span>LOW</span><span className="text-primary">MEDIUM</span><span className="text-destructive">HIGH</span></div></div></div>
      </Panel>
    </div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2">
      <Panel title="Flow vectors" eyebrow="DIRECTIONAL FIELD / 1 MIN"><div className="p-4"><div className="relative h-[160px] overflow-hidden border border-border bg-[#101b27] grid-surface">{[...Array(10)].map((_, i) => <span key={i} className="absolute flex items-center text-secondary" style={{ left: `${8 + (i * 13) % 78}%`, top: `${15 + (i * 29) % 63}%`, transform: `rotate(${camera.density > 60 ? -8 : 4}deg)` }}><span className="h-px w-10 bg-secondary/70" /><span className="border-y-4 border-l-4 border-y-transparent border-l-secondary/70" /></span>)}<div className="absolute bottom-2 left-2 data-mono text-[8px] text-muted-foreground">VECTOR MAGNITUDE · 0.4—1.8 M/S</div></div><div className="mt-3 flex items-center justify-between data-mono text-[9px] text-muted-foreground"><span>INBOUND <b className="text-primary">{state.zones[0].inflow}</b> / MIN</span><span>OUTBOUND <b className="text-secondary">{state.zones[0].outflow}</b> / MIN</span><span>CONFLICT <b className="text-destructive">{state.zones[0].directionConflict}%</b></span></div></div></Panel>
      <Panel title="Detection channels" eyebrow="MODEL OUTPUT"><div className="divide-y divide-border">{detections.map(({ label, Icon, value, tone }) => <div className="flex items-center gap-3 px-4 py-3" key={label}><Icon size={15} className={tone} /><span className="text-[11px] text-muted-foreground">{label}</span><span className={`data-mono ml-auto text-[9px] ${tone}`}>{value}</span></div>)}</div></Panel>
    </div>
  </div>;
}