import { useMemo, useState } from 'react';
import { CalendarClock, CheckCircle2, ChevronDown, Download, Filter, ListFilter, RefreshCw, Search, SlidersHorizontal } from 'lucide-react';
import { useSentinel } from '@/hooks/use-sentinel';
import { PageIntro, Panel, ScenarioControls, SeverityBadge } from '@/components/sentinel-shell';
import type { Severity } from '@/lib/sentinel';

const filters = ['ALL', 'AI', 'CAMERA', 'SYSTEM', 'HARDWARE', 'WARNING', 'CRITICAL', 'CONFIGURATION'];
const severities: ('ALL' | Severity)[] = ['ALL', 'info', 'watch', 'urgent', 'critical'];
export default function Events() {
  const { state } = useSentinel();
  const [category, setCategory] = useState('ALL');
  const [severity, setSeverity] = useState<'ALL' | Severity>('ALL');
  const [query, setQuery] = useState('');
  const [ack, setAck] = useState(false);
  const visible = useMemo(() => state.events.filter((event) => (category === 'ALL' || event.category === category) && (severity === 'ALL' || event.severity === severity) && event.message.toLowerCase().includes(query.toLowerCase())), [state.events, category, severity, query]);
  const exportEvents=()=>{const rows=[['timestamp','category','severity','message'],...visible.map(event=>[event.timestamp,event.category,event.severity,event.message])];const csv=rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const link=document.createElement('a');link.href=url;link.download='crowdguard-events.csv';link.click();URL.revokeObjectURL(url)};
  return <div className="enter-rise">
    <PageIntro eyebrow="05 / AUDIT TRAIL" title="Event Log" description="A chronological record of model decisions, device state changes, and operator actions. Local demo events will map cleanly to a WebSocket event stream." action={<button onClick={() => setAck((value) => !value)} className={`flex items-center gap-2 border px-3 py-2 text-[9px] uppercase tracking-[.12em] ${ack ? 'border-secondary/35 bg-secondary/10 text-secondary' : 'border-border text-muted-foreground'}`} data-testid="button-acknowledge-events">{ack ? <CheckCircle2 size={14} /> : <CalendarClock size={14} />}{ack ? 'Queue acknowledged' : 'Acknowledge queue'}</button>} />
    <ScenarioControls />
    <Panel title="Chronological event stream" eyebrow={`${visible.length} EVENTS · SQLITE + LIVE STREAM`} action={<div className="flex items-center gap-2"><button onClick={() => setQuery('')} className="text-muted-foreground hover:text-foreground" aria-label="Refresh event stream" data-testid="button-refresh-events"><RefreshCw size={13} /></button><button onClick={exportEvents} className="text-muted-foreground hover:text-foreground" aria-label="Export events" data-testid="button-export-events"><Download size={14} /></button></div>}>
      <div className="border-b border-border bg-muted/25 p-3"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-1">{filters.map((item) => <button key={item} onClick={() => setCategory(item)} className={`border px-2 py-1.5 data-mono text-[8px] tracking-[.12em] ${category === item ? 'border-primary/50 bg-primary/10 text-primary' : 'border-border text-muted-foreground hover:bg-muted'}`} data-testid={`button-filter-category-${item.toLowerCase()}`}>{item}</button>)}</div><div className="flex items-center gap-2"><div className="flex items-center gap-2 border border-border bg-card px-2.5 py-1.5"><Search size={12} className="text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search event messages" className="w-[170px] bg-transparent text-[10px] outline-none placeholder:text-muted-foreground/60" data-testid="input-search-events" /></div><div className="flex items-center gap-1 border border-border bg-card px-2 py-1.5"><SlidersHorizontal size={12} className="text-muted-foreground" /><select value={severity} onChange={(event) => setSeverity(event.target.value as 'ALL' | Severity)} className="bg-transparent data-mono text-[8px] uppercase text-muted-foreground outline-none" data-testid="select-filter-severity">{severities.map((item) => <option key={item} value={item} className="bg-card">{item}</option>)}</select><ChevronDown size={11} className="text-muted-foreground" /></div></div></div></div>
      {visible.length ? <div className="divide-y divide-border">{visible.map((event, index) => <div className="group grid gap-3 px-4 py-4 transition-colors hover:bg-muted/20 sm:grid-cols-[115px_75px_75px_1fr] sm:items-center" key={`${event.timestamp}-${index}`}><div className="data-mono text-[9px] text-muted-foreground">{event.timestamp}</div><div><span className="data-mono text-[8px] tracking-[.1em] text-foreground">{event.category}</span></div><div><SeverityBadge severity={event.severity} /></div><div className="flex items-center gap-2 text-[11px] text-foreground"><span className={`h-1.5 w-1.5 shrink-0 rounded-full ${event.severity === 'critical' || event.severity === 'urgent' ? 'bg-destructive' : event.severity === 'watch' ? 'bg-primary' : 'bg-secondary'}`} />{event.message}<ChevronDown size={13} className="ml-auto rotate-[-90deg] text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100" /></div></div>)}</div> : <div className="flex min-h-[220px] flex-col items-center justify-center px-5 text-center"><div className="grid h-10 w-10 place-items-center border border-secondary/30 bg-secondary/10 text-secondary"><ListFilter size={17} /></div><div className="mt-3 text-[12px] font-semibold">No matching events</div><p className="mt-1 max-w-[280px] text-[10px] text-muted-foreground">Try clearing the filters or selecting a different severity channel.</p><button onClick={() => { setCategory('ALL'); setSeverity('ALL'); setQuery(''); }} className="mt-4 border border-primary/35 px-3 py-2 text-[9px] uppercase tracking-[.12em] text-primary" data-testid="button-clear-event-filters">Clear filters</button></div>}
      <div className="flex items-center justify-between border-t border-border bg-muted/20 px-4 py-3"><div className="flex items-center gap-2 data-mono text-[8px] text-muted-foreground"><Filter size={11} /> Showing {visible.length} of {state.events.length} buffered events</div><span className="data-mono text-[8px] text-secondary">RETENTION · 24 HR</span></div>
    </Panel>
  </div>;
}
