import { useState } from 'react';
import { Camera, DoorOpen, GitFork, Plus, RadioTower, Trash2 } from 'lucide-react';
import { PageIntro, Panel } from '@/components/sentinel-shell';
import { useSentinel } from '@/hooks/use-sentinel';
import { apiFetch } from '@/services/api';
import type { Camera as CameraModel, Exit, Junction, Sentinel, Zone } from '@/types/sentinel';

export default function FacilityConfiguration(){
 const {snapshot,facilities,selectFacility,refresh}=useSentinel();const [kind,setKind]=useState<'camera'|'zone'|'exit'|'junction'|'sentinel'|null>(null);const [name,setName]=useState('');const [busy,setBusy]=useState(false);const f=snapshot?.facility;
 if(!f)return <div className="panel p-8 text-sm text-muted-foreground">FACILITY CONFIG ERROR — start the FastAPI backend, then retry.</div>;
 async function add(){if(!name.trim())return;setBusy(true);const id=name.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')+'_'+Date.now().toString().slice(-4);if(kind==='camera'){const value:Partial<CameraModel>={id,facility_id:f!.id,name,enabled:true,status:'ONLINE',source:'demo://generated',zone_ids:[],camera_type:'GENERAL',ai_enabled:true,description:'Operator-added camera'};await apiFetch('/cameras',{method:'POST',body:JSON.stringify(value)})}else if(kind==='zone'){const value:Partial<Zone>={id,facility_id:f!.id,name,type:'GENERAL',camera_ids:[],risk:0,crowd_state:'NORMAL',enabled:true,map_x:50,map_y:50};await apiFetch('/zones',{method:'POST',body:JSON.stringify(value)})}else if(kind==='exit'){const zone=f!.zones[0];const value:Partial<Exit>={id,facility_id:f!.id,name,zone_id:zone.id,enabled:true,availability:1,risk:zone.risk,status:'AVAILABLE',capacity:100,camera_ids:[],current_inflow:0,current_outflow:0};await apiFetch('/exits',{method:'POST',body:JSON.stringify(value)})}else if(kind==='junction'){const value:Partial<Junction>={id,name,connected_exit_ids:[],sentinel_ids:[],map_x:50,map_y:50};await apiFetch('/junctions',{method:'POST',body:JSON.stringify(value)})}else if(kind==='sentinel'){if(!f!.junctions.length)throw new Error('Add a junction first');const value:Partial<Sentinel>={id,name,junction_id:f!.junctions[0].id,nearby_exit_ids:[],device_id:`mock-${id}`,connected:true,hardware_state:{arm_state:'NORMAL',display_message:'NORMAL',audio:'NONE',audio_state:'IDLE',led_routes:{}}};await apiFetch('/sentinels',{method:'POST',body:JSON.stringify(value)})}setName('');setKind(null);await refresh();setBusy(false)}
 async function remove(type:'cameras'|'exits',id:string){await apiFetch(`/${type}/${id}`,{method:'DELETE'});await refresh()}
 async function toggle(type:'cameras'|'exits',item:{id:string;enabled:boolean}){await apiFetch(`/${type}/${item.id}`,{method:'PATCH',body:JSON.stringify({enabled:!item.enabled})});await refresh()}
 return <div className="enter-rise"><PageIntro eyebrow="06 / SYSTEM TOPOLOGY" title="Facility Configuration" description="Configure scalable multi-camera, multi-zone, multi-exit, multi-junction deployments. The current physical prototype remains a small subset of this architecture." action={<select value={f.id} onChange={e=>void selectFacility(e.target.value)} className="border border-primary/40 bg-card px-3 py-2 data-mono text-[10px] text-primary">{facilities.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}/>
 <section className="mb-5 border border-secondary/30 bg-secondary/5 p-4"><div className="data-mono text-[9px] text-secondary">{f.id==='competition_prototype'?'CURRENT PROTOTYPE':'SCALABILITY DEMONSTRATION'}</div><div className="mt-2 text-sm font-semibold">{f.name}</div><p className="mt-1 text-[11px] text-muted-foreground">{f.description}</p><div className="mt-4 flex flex-wrap gap-2">{(['camera','zone','exit','junction','sentinel'] as const).map(item=><button key={item} onClick={()=>setKind(item)} className="border border-primary/30 px-2.5 py-1.5 data-mono text-[8px] text-primary">+ ADD {item.toUpperCase()}</button>)}</div></section>
 <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Count icon={Camera} label="Cameras" value={f.cameras.length}/><Count icon={RadioTower} label="Zones" value={f.zones.length}/><Count icon={DoorOpen} label="Exits" value={f.exits.length}/><Count icon={GitFork} label="Junctions" value={f.junctions.length}/><Count icon={RadioTower} label="Sentinels" value={f.sentinels.length}/></div>
 <div className="grid gap-5 xl:grid-cols-2"><Panel title="Camera Management" eyebrow={`${f.cameras.length} CONFIGURED`} action={<button onClick={()=>setKind('camera')} className="flex items-center gap-1 text-[9px] text-primary"><Plus size={13}/> ADD CAMERA</button>}><div className="divide-y divide-border">{f.cameras.map(c=><Row key={c.id} title={c.name} detail={`${c.camera_type} · ${c.zone_ids.length} zone(s) · ${c.status}`} enabled={c.enabled} onToggle={()=>void toggle('cameras',c)} onRemove={()=>void remove('cameras',c.id)}/>)}</div></Panel>
 <Panel title="Exit Management" eyebrow={`${f.exits.length} CONFIGURED`} action={<button onClick={()=>setKind('exit')} className="flex items-center gap-1 text-[9px] text-primary"><Plus size={13}/> ADD EXIT</button>}><div className="divide-y divide-border">{f.exits.map(e=><Row key={e.id} title={e.name} detail={`${e.status} · capacity ${e.capacity} · risk ${Math.round(e.risk)}%`} enabled={e.enabled} onToggle={()=>void toggle('exits',e)} onRemove={()=>void remove('exits',e.id)}/>)}</div></Panel></div>
 <div className="mt-5 grid gap-5 xl:grid-cols-2"><Panel title="Zones and camera coverage" eyebrow="MANY-TO-MANY ASSIGNMENT"><div className="divide-y divide-border">{f.zones.map(z=><div key={z.id} className="p-4"><div className="flex justify-between text-[11px] font-semibold"><span>{z.name}</span><span className="data-mono text-primary">RISK {Math.round(z.risk)}</span></div><div className="mt-1 text-[9px] text-muted-foreground">{z.type} · {z.camera_ids.length} camera(s) · {z.crowd_state}</div></div>)}</div></Panel><Panel title="Junctions and Sentinels" eyebrow="DISTRIBUTED GUIDANCE" action={<div className="flex gap-3"><button onClick={()=>setKind('junction')} className="text-[9px] text-primary">+ JUNCTION</button><button onClick={()=>setKind('sentinel')} className="text-[9px] text-primary">+ SENTINEL</button></div>}><div className="divide-y divide-border">{f.junctions.map(j=><div className="p-4" key={j.id}><div className="text-[11px] font-semibold">{j.name}</div><div className="mt-1 text-[9px] text-muted-foreground">{j.connected_exit_ids.length} connected exits · {j.sentinel_ids.length} Sentinel(s)</div></div>)}{f.sentinels.map(s=><div className="p-4" key={s.id}><div className="text-[11px] font-semibold text-secondary">{s.name}</div><div className="mt-1 text-[9px] text-muted-foreground">{s.device_id} · junction {s.junction_id} · {s.connected?'connected':'offline'}</div></div>)}</div></Panel></div>
 {kind&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="w-full max-w-md border border-border bg-card p-5"><div className="text-sm font-semibold">Add {kind}</div><p className="mt-1 text-[10px] text-muted-foreground">Creates a persistent configuration record. Streams and real AI remain configuration-ready.</p><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder={`${kind} name`} className="mt-4 w-full border border-border bg-background px-3 py-2 text-sm outline-none focus:border-primary"/><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setKind(null)} className="border border-border px-3 py-2 text-[10px]">Cancel</button><button disabled={busy||!name.trim()} onClick={()=>void add()} className="border border-primary bg-primary/10 px-3 py-2 text-[10px] text-primary">{busy?'Saving…':'Add'}</button></div></div></div>}</div>
}
function Count({icon:Icon,label,value}:{icon:typeof Camera;label:string;value:number}){return <div className="panel p-4"><Icon size={15} className="text-secondary"/><div className="data-mono mt-3 text-2xl text-primary">{value}</div><div className="mt-1 text-[10px] text-muted-foreground">{label}</div></div>}
function Row({title,detail,enabled,onToggle,onRemove}:{title:string;detail:string;enabled:boolean;onToggle:()=>void;onRemove:()=>void}){return <div className="flex items-center gap-3 p-4"><button onClick={onToggle} className={`h-4 w-8 rounded-full p-0.5 ${enabled?'bg-secondary':'bg-muted'}`}><span className={`block h-3 w-3 rounded-full bg-background transition-transform ${enabled?'translate-x-4':''}`}/></button><div className="min-w-0 flex-1"><div className="text-[11px] font-semibold">{title}</div><div className="mt-1 truncate text-[9px] text-muted-foreground">{detail}</div></div><button onClick={onRemove} aria-label={`Remove ${title}`} className="text-muted-foreground hover:text-destructive"><Trash2 size={14}/></button></div>}
