import { useState } from 'react';
import { AlertOctagon, Cpu, RadioTower, RotateCcw, ShieldAlert } from 'lucide-react';
import { PageIntro, Panel, ScenarioControls } from '@/components/sentinel-shell';
import { useSentinel } from '@/hooks/use-sentinel';
import { apiFetch } from '@/services/api';
import type { BackendSnapshot } from '@/types/sentinel';

export default function Hardware(){const {snapshot,refresh}=useSentinel();const [confirm,setConfirm]=useState<string|null>(null);const f=snapshot?.facility;
 async function command(action:'NORMAL'|'REDIRECT_TO_EXIT'|'CRITICAL'|'RESET',exit?:string){await apiFetch<BackendSnapshot>('/control/manual',{method:'POST',body:JSON.stringify({action,recommended_exit_id:exit})});setConfirm(null);await refresh()}
 return <div className="enter-rise"><PageIntro eyebrow="04 / FIELD SYSTEMS" title="Hardware" description="Monitor stationary CrowdGuard Sentinel units. Each unit represents an ESP32, servo guidance arm, WS2812B routes, colour display, DFPlayer Mini, and speaker." action={<div className="border border-primary/35 bg-primary/5 px-3 py-2 data-mono text-[9px] text-primary">{snapshot?.automatic_control?'AI CONTROL ACTIVE':'MANUAL CONTROL ACTIVE'}</div>}/><ScenarioControls/>
 {!f?<div className="panel p-8 text-sm text-muted-foreground">NO DATA — backend offline.</div>:<><div className="grid gap-5 xl:grid-cols-[1.3fr_1fr]"><Panel title="Configured Sentinels" eyebrow={`${f.sentinels.length} UNIT(S)`}><div className="divide-y divide-border">{f.sentinels.map(s=><div className="p-4" key={s.id}><div className="flex items-center gap-3"><span className={`grid h-9 w-9 place-items-center border ${s.connected?'border-secondary/30 text-secondary':'border-destructive/30 text-destructive'}`}><Cpu size={16}/></span><div><div className="text-[12px] font-semibold">{s.name}</div><div className="data-mono mt-1 text-[9px] text-muted-foreground">{s.device_id} · {s.connected?'MOCK CONNECTED':'DISCONNECTED'}</div></div></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><State label="GUIDANCE ARM" value={s.hardware_state.arm_state}/><State label="DISPLAY" value={s.hardware_state.display_message}/><State label="AUDIO" value={`${s.hardware_state.audio} · ${s.hardware_state.audio_state}`}/>{Object.entries(s.hardware_state.led_routes).map(([id,value])=><State key={id} label={`${f.exits.find(e=>e.id===id)?.name??id} LED ROUTE`} value={value}/>)}</div></div>)}</div></Panel><Panel title="Hardware boundary" eyebrow="LOCAL / BACKEND CONTROLLED"><div className="p-4 text-[10px] leading-relaxed text-muted-foreground"><RadioTower size={18} className="mb-3 text-secondary"/>The dashboard never sends commands directly to ESP32. FastAPI validates the selected exit and invokes the configured hardware client. This demonstration uses MockESP32Client and requires no physical unit.</div></Panel></div>
 <Panel title="Manual control" eyebrow="DYNAMIC EXIT COMMANDS" className="mt-5"><div className="grid gap-px bg-border sm:grid-cols-2 xl:grid-cols-4"><Control label="NORMAL" onClick={()=>void command('NORMAL')} icon={RotateCcw}/>{f.exits.filter(e=>e.enabled&&e.status!=='CLOSED'&&e.status!=='RESTRICTED').map(e=><Control key={e.id} label={`REDIRECT → ${e.name}`} onClick={()=>void command('REDIRECT_TO_EXIT',e.id)} icon={RadioTower}/>) }<Control label="CRITICAL MODE" onClick={()=>setConfirm('critical')} icon={ShieldAlert}/><Control label="RESET" onClick={()=>void command('RESET')} icon={RotateCcw}/></div></Panel></>}
 {confirm&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="max-w-sm border border-destructive/50 bg-card p-5"><AlertOctagon className="text-destructive"/><div className="mt-3 text-sm font-semibold">Confirm critical mode</div><p className="mt-2 text-[10px] text-muted-foreground">Use only after checking the physical venue and operator procedures.</p><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setConfirm(null)} className="border border-border px-3 py-2 text-[10px]">Cancel</button><button onClick={()=>void command('CRITICAL')} className="border border-destructive bg-destructive/10 px-3 py-2 text-[10px] text-destructive">Confirm</button></div></div></div>}</div>}
function State({label,value}:{label:string;value:string}){return <div className="border border-border bg-muted/20 p-3"><div className="data-mono text-[8px] text-muted-foreground">{label}</div><div className="data-mono mt-2 text-[9px] text-secondary">{value}</div></div>}
function Control({label,onClick,icon:Icon}:{label:string;onClick:()=>void;icon:typeof RotateCcw}){return <button onClick={onClick} className="flex min-h-24 flex-col items-start justify-between bg-card p-4 text-left hover:bg-muted/30"><Icon size={16} className="text-primary"/><span className="data-mono text-[9px] text-foreground">{label}</span></button>}
