import { useState } from 'react';
import { AlertOctagon, Check, ChevronRight, Cpu, ExternalLink, LockKeyhole, Power, RotateCcw, Siren, Volume2, Wifi } from 'lucide-react';
import { useSentinel } from '@/hooks/use-sentinel';
import { PageIntro, Panel, ScenarioControls } from '@/components/sentinel-shell';

export default function Hardware() {
  const { state } = useSentinel();
  const [override, setOverride] = useState<string | null>(null);
  const [confirming, setConfirming] = useState<string | null>(null);
  const hardware = [
    { device: 'CrowdGuard Edge Node 01', category: 'Inference gateway', status: 'online', latency: 42, state: 'PROCESSING', message: '3 camera streams · 18.2 GB free', icon: Cpu },
    { device: 'Mobile Unit R-04', category: 'Guidance robot', status: state.robot.arm === 'ACTIVE' ? 'online' : 'warning', latency: 84, state: state.robot.arm, message: state.robot.display, icon: Wifi },
    { device: 'ESP32 Relay Bus', category: 'Exit actuators', status: 'online', latency: 18, state: 'ARMED', message: '4 relay channels · heartbeat 2s', icon: Power },
    { device: 'Thermal Array / 6', category: 'Environmental sensors', status: 'online', latency: 26, state: 'SYNCED', message: 'Ambient + concentration signals', icon: Siren },
  ];
  const dangerous = (id: string) => { setConfirming(null); setOverride(id); };
  return <div className="enter-rise">
    <PageIntro eyebrow="04 / FIELD SYSTEMS" title="Hardware" description="Monitor edge devices and issue deliberate manual overrides. Dangerous actions require a second confirmation so the operator stays in the loop." action={<div className="flex items-center gap-2 border border-secondary/25 bg-secondary/5 px-3 py-2"><span className="status-pulse h-2 w-2 rounded-full bg-secondary" /><span className="data-mono text-[9px] uppercase tracking-[.12em] text-secondary">All critical links healthy</span></div>} />
    <ScenarioControls />
    <div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]">
      <Panel title="Device health" eyebrow="EDGE / RELAY / ROBOT TELEMETRY"><div className="divide-y divide-border">{hardware.map(({ device, category, status, latency, state: deviceState, message, icon: Icon }) => <div className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center" key={device}><div className={`grid h-10 w-10 shrink-0 place-items-center border ${status === 'online' ? 'border-secondary/30 bg-secondary/10 text-secondary' : 'border-primary/30 bg-primary/10 text-primary'}`}><Icon size={17} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2 text-[12px] font-semibold">{device}<span className={`data-mono border px-1.5 py-0.5 text-[8px] uppercase ${status === 'online' ? 'border-secondary/25 text-secondary' : 'border-primary/25 text-primary'}`}>{status}</span></div><div className="mt-1 text-[10px] text-muted-foreground">{category} · {message}</div></div><div className="flex items-center gap-6 sm:text-right"><div><div className="data-mono text-[10px] text-foreground">{deviceState}</div><div className="data-mono mt-1 text-[8px] text-muted-foreground">{latency}ms latency</div></div><ChevronRight size={15} className="text-muted-foreground" /></div></div>)}</div></Panel>
      <Panel title="Bus diagnostics" eyebrow="ESP32 RELAY BUS / LIVE"><div className="p-4"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2 text-[11px] font-semibold"><span className="status-pulse h-2 w-2 rounded-full bg-secondary" /> Channel integrity</div><span className="data-mono text-[10px] text-secondary">100%</span></div>{[['Exit A signal', 'GREEN / HOLD', state.robot.exitALights.includes('RED')], ['Exit B signal', 'GREEN / OPEN', state.robot.exitBLights.includes('RED')], ['Audio relay', state.robot.audio, false], ['Beacon relay', state.robot.beacon, state.robot.beacon !== 'OFF']].map(([label, value, alert]) => <div className="flex items-center justify-between border-b border-border py-3 last:border-0" key={String(label)}><span className="text-[10px] text-muted-foreground">{label}</span><span className={`data-mono text-[9px] ${alert ? 'text-destructive' : 'text-secondary'}`}>{value}</span></div>)}<div className="mt-4 flex gap-2 border border-border bg-muted/30 p-3 text-[9px] leading-relaxed text-muted-foreground"><LockKeyhole size={14} className="shrink-0 text-primary" />Manual controls are logged, rate-limited, and require operator acknowledgement.</div></div></Panel>
    </div>
    <Panel title="Manual override controls" eyebrow="OPERATOR AUTHORITY / DUAL CONFIRMATION" className="mt-5"><div className="grid gap-px bg-border md:grid-cols-3">{[{ id: 'robot', label: 'Robot guidance', detail: override === 'robot' ? 'Command sent · guidance active' : 'Pause or resume R-04 route', icon: RotateCcw }, { id: 'audio', label: 'Emergency audio', detail: override === 'audio' ? 'Broadcast channel armed' : 'Arm evacuation broadcast', icon: Volume2 }, { id: 'lights', label: 'All exit lighting', detail: override === 'lights' ? 'All exits set to open' : 'Set both exits to open', icon: Siren }].map(({ id, label, detail, icon: Icon }) => <div className="bg-card p-4" key={id}><div className="flex items-start justify-between"><div className="grid h-9 w-9 place-items-center border border-primary/25 bg-primary/10 text-primary"><Icon size={15} /></div>{override === id && <span className="grid h-5 w-5 place-items-center rounded-full bg-secondary text-background"><Check size={12} /></span>}</div><div className="mt-4 text-[11px] font-semibold">{label}</div><div className="mt-1 min-h-[30px] text-[10px] leading-relaxed text-muted-foreground">{detail}</div>{confirming === id ? <div className="mt-3 flex gap-2"><button onClick={() => dangerous(id)} className="flex-1 border border-destructive bg-destructive/15 py-2 text-[9px] font-semibold uppercase text-destructive" data-testid={`button-confirm-${id}`}>Confirm</button><button onClick={() => setConfirming(null)} className="border border-border px-3 py-2 text-[9px] text-muted-foreground" data-testid={`button-cancel-${id}`}>Cancel</button></div> : <button onClick={() => setConfirming(id)} className="mt-3 flex w-full items-center justify-center gap-2 border border-primary/35 bg-primary/5 py-2 text-[9px] font-semibold uppercase tracking-[.12em] text-primary hover:bg-primary/10" data-testid={`button-override-${id}`}>{override === id ? 'Re-issue command' : 'Request override'} <ExternalLink size={11} /></button>}</div>)}</div></Panel>
    {confirming && <div className="fixed bottom-5 right-5 z-30 flex max-w-[330px] items-start gap-3 border border-destructive/55 bg-card p-4 shadow-2xl"><AlertOctagon size={20} className="shrink-0 text-destructive" /><div><div className="text-[11px] font-semibold">Confirm dangerous command</div><p className="mt-1 text-[10px] leading-relaxed text-muted-foreground">This command changes physical crowd guidance hardware. Continue only if you have verified the live field.</p></div></div>}
  </div>;
}