import { BrainCircuit, ChevronRight, Flame, Radio, ShieldAlert, Thermometer, Waves } from 'lucide-react';
import { useSentinel } from '@/hooks/use-sentinel';
import { PageIntro, Panel, ScenarioControls } from '@/components/sentinel-shell';

export default function Intelligence() {
  const { state } = useSentinel();
  const score = state.analysis.risk;
  return <div className="enter-rise">
    <PageIntro eyebrow="03 / MODEL OBSERVABILITY" title="AI Intelligence" description="See the evidence behind each recommendation. CrowdGuard turns edge vision and thermal signals into a decision an operator can audit." action={<div className="flex items-center gap-2 border border-primary/25 bg-primary/5 px-3 py-2"><BrainCircuit size={14} className="text-primary" /><span className="data-mono text-[9px] text-primary">MODEL V4.2 · INFERENCE ONLINE</span></div>} />
    <ScenarioControls />
    <div className="grid gap-5 xl:grid-cols-[1fr_1.45fr]">
      <Panel title="Current crowd state" eyebrow="FUSED OUTPUT">
        <div className="p-5"><div className="flex items-center gap-4"><div className={`relative grid h-28 w-28 place-items-center rounded-full border-8 ${score > 80 ? 'border-destructive/70' : score > 55 ? 'border-primary/70' : 'border-secondary/70'}`}><div className="text-center"><div className="data-mono text-[30px] font-semibold text-foreground">{score}</div><div className="data-mono text-[8px] text-muted-foreground">RISK / 100</div></div><span className={`absolute inset-[-8px] rounded-full border border-dashed ${score > 80 ? 'border-destructive/35' : 'border-primary/35'} animate-[spin_18s_linear_infinite]`} /></div><div><div className={`data-mono text-[13px] font-semibold ${score > 80 ? 'text-destructive' : score > 55 ? 'text-primary' : 'text-secondary'}`}>{state.analysis.state}</div><p className="mt-2 max-w-[240px] text-[11px] leading-relaxed text-muted-foreground">Model confidence is <span className="text-foreground">{state.analysis.confidence}%</span> from {state.cameras.length} synchronized camera streams.</p></div></div><div className="mt-6 space-y-3 border-t border-border pt-4">{[['Ripple signal', state.analysis.rippleDetected ? 'DETECTED' : 'CLEAR', state.analysis.rippleDetected ? 'text-destructive' : 'text-secondary'], ['Propagation', state.analysis.propagation, 'text-foreground'], ['Model window', '12.4 seconds', 'text-foreground']].map(([label, value, tone]) => <div className="flex justify-between text-[10px]" key={String(label)}><span className="text-muted-foreground">{label}</span><span className={`data-mono ${tone}`}>{value}</span></div>)}</div></div>
      </Panel>
      <Panel title="Signal contribution" eyebrow="WHY THE MODEL MOVED" action={<span className="data-mono text-[9px] text-muted-foreground">WEIGHTED / 100</span>}>
        <div className="divide-y divide-border">{state.explanations.map((item, index) => <div className="p-4" key={item.signal}><div className="mb-2 flex items-center justify-between"><div className="flex items-center gap-2 text-[11px] font-medium"><span className="data-mono text-[9px] text-muted-foreground">0{index + 1}</span>{item.signal}</div><div className="flex items-center gap-3"><span className={`data-mono text-[9px] ${item.status === 'elevated' || item.status === 'slowing' ? 'text-primary' : 'text-secondary'}`}>{item.value} {item.unit}</span><span className="data-mono text-[9px] text-muted-foreground">{item.contribution}%</span></div></div><div className="h-1 bg-muted"><div className={`h-full ${item.status === 'elevated' ? 'bg-destructive' : item.status === 'slowing' ? 'bg-primary' : 'bg-secondary'}`} style={{ width: `${item.contribution * 2.45}%` }} /></div><div className="mt-2 text-[9px] text-muted-foreground">{item.tooltip}</div></div>)}</div>
      </Panel>
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_1fr]">
      <Panel title="Ripple / disturbance field" eyebrow="TEMPORAL PROPAGATION / CENTRAL PLAZA"><div className="relative h-[280px] overflow-hidden bg-[#101b27] p-5"><div className="absolute inset-0 grid-surface opacity-50" />{state.analysis.rippleDetected ? <><div className="absolute left-[48%] top-[52%] h-5 w-5 -translate-x-1/2 -translate-y-1/2 rounded-full border border-destructive bg-destructive/35" /><span className="absolute left-[48%] top-[52%] h-20 w-20 -translate-x-1/2 -translate-y-1/2 rounded-full border border-destructive/45 animate-[ping_3s_ease-out_infinite]" /><span className="absolute left-[48%] top-[52%] h-36 w-36 -translate-x-1/2 -translate-y-1/2 rounded-full border border-destructive/30 animate-[ping_3s_ease-out_700ms_infinite]" /><span className="absolute left-[48%] top-[52%] h-56 w-56 -translate-x-1/2 -translate-y-1/2 rounded-full border border-destructive/20 animate-[ping_3s_ease-out_1400ms_infinite]" /></> : <div className="absolute inset-0 grid place-items-center"><div className="text-center"><Waves size={30} className="mx-auto text-secondary/60" /><div className="data-mono mt-3 text-[10px] text-secondary">NO DISTURBANCE SIGNATURE</div><div className="mt-1 text-[10px] text-muted-foreground">Flow field within expected variance</div></div></div>}<div className="absolute bottom-4 left-5 right-5 flex items-end justify-between"><div><div className="data-mono text-[9px] uppercase text-muted-foreground">Signal strength</div><div className={`data-mono mt-1 text-[16px] ${state.analysis.rippleDetected ? 'text-destructive' : 'text-secondary'}`}>{state.analysis.rippleStrength || '—'}{state.analysis.rippleDetected && '%'}</div></div><div className="text-right"><div className="data-mono text-[9px] uppercase text-muted-foreground">Vector</div><div className="data-mono mt-1 text-[11px] text-foreground">{state.analysis.propagation}</div></div></div></div></Panel>
      <Panel title="Thermal sensor input" eyebrow="ENVIRONMENTAL CONTEXT"><div className="p-4"><div className="mb-4 flex items-center gap-3 border border-border bg-muted/30 p-3"><div className="grid h-9 w-9 place-items-center border border-destructive/25 bg-destructive/10 text-destructive"><Thermometer size={17} /></div><div><div className="data-mono text-[20px] text-foreground">{state.analysis.thermal.toFixed(1)}°C</div><div className="text-[10px] text-muted-foreground">dense cluster average · 6 nodes</div></div><div className="ml-auto"><Flame size={16} className={state.analysis.thermal > 38 ? 'text-destructive' : 'text-primary'} /></div></div><div className="space-y-4">{[['Ambient', `${state.analysis.ambient}°C`, 40], ['Humidity', `${state.analysis.humidity}%`, state.analysis.humidity], ['Concentration', `${Math.round(state.analysis.thermal * 1.7)} tracks/m²`, Math.min(100, state.analysis.thermal * 1.9)]].map(([label, value, width]) => <div key={String(label)}><div className="mb-1.5 flex justify-between text-[10px]"><span className="text-muted-foreground">{label}</span><span className="data-mono text-foreground">{value}</span></div><div className="h-1 bg-muted"><div className="h-full bg-primary" style={{ width: `${width}%` }} /></div></div>)}</div><div className="mt-5 flex items-center gap-2 border-t border-border pt-4 text-[10px] text-muted-foreground"><Radio size={13} className="text-secondary" /> Sensor fusion healthy <span className="ml-auto data-mono text-secondary">SYNCED</span></div></div></Panel>
    </div>
    <Panel title="Risk predictions by zone" eyebrow="NEXT 60 SECONDS" className="mt-5"><div className="grid gap-px bg-border md:grid-cols-2">{state.predictions.map((prediction) => <div className="bg-card p-4" key={prediction.zone}><div className="flex items-center justify-between"><span className="text-[12px] font-semibold">{prediction.zone}</span><span className={`data-mono text-[18px] ${prediction.risk > 75 ? 'text-destructive' : prediction.risk > 45 ? 'text-primary' : 'text-secondary'}`}>{prediction.risk}</span></div><div className="mt-3 flex items-center justify-between text-[10px]"><span className="text-muted-foreground">{prediction.label} · trend {prediction.trend}</span><span className="data-mono text-secondary">Route {prediction.recommendedExit}</span></div><div className="mt-3 flex items-center gap-2 text-[10px] text-muted-foreground"><ShieldAlert size={13} className={prediction.risk > 75 ? 'text-destructive' : 'text-primary'} /> {prediction.intervention}<ChevronRight size={13} className="ml-auto" /></div></div>)}</div></Panel>
  </div>;
}