import { useMemo } from 'react';
import { Activity, ArrowRight, Bot, CircleAlert, Gauge, ShieldCheck, TrendingDown, TrendingUp, Users } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { MapPanel, PageIntro, Panel, ScenarioControls } from '@/components/sentinel-shell';
import { useSentinel } from '@/hooks/use-sentinel';
import { apiFetch } from '@/services/api';
import type { BackendSnapshot } from '@/types/sentinel';

export default function LiveControl(){
  const {snapshot,connection,refresh}=useSentinel();
  const chart=useMemo(()=>snapshot?.risk_timeline.map((sample)=>({time:new Date(sample.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}),risk:sample.risk,intervention:sample.intervention}))??[],[snapshot]);
  const marker=chart.find((sample)=>sample.intervention)?.time;
  if(!snapshot)return <div className="enter-rise"><PageIntro eyebrow="01 / COMMAND SURFACE" title="Live Control" description="Waiting for the CrowdGuard backend. No simulated browser values are substituted."/><div className="panel grid min-h-72 place-items-center text-center"><div><div className="data-mono text-[11px] text-primary">{connection==='connecting'?'CONNECTING':'BACKEND OFFLINE'}</div><button onClick={()=>void refresh()} className="mt-4 border border-primary/40 px-3 py-2 data-mono text-[9px] text-primary">RETRY</button></div></div></div>;

  const {facility,prediction,decision,intervention}=snapshot;
  const affected=facility.zones.find((zone)=>zone.id===prediction.affected_zone_id);
  const recommended=facility.exits.find((exit)=>exit.id===decision.recommended_exit_id);
  const previous=chart.at(-2)?.risk??prediction.risk;
  const trend=prediction.risk<previous?'IMPROVING':prediction.risk>previous?'WORSENING':'STABLE';
  const critical=prediction.risk>=90;

  async function toggleAutomatic(){await apiFetch<BackendSnapshot>('/control/auto',{method:'POST',body:JSON.stringify({enabled:!snapshot!.automatic_control})});await refresh()}

  return <div className="enter-rise">
    <PageIntro eyebrow="01 / COMMAND SURFACE" title="Live Control" description={`Current backend state for ${facility.name}. ${prediction.simulated?'All AI metrics are explicitly simulated.':'Metrics are provider-derived.'}`} action={<div className={`flex items-center gap-2 border px-3 py-2 ${connection==='open'?'border-secondary/30 text-secondary':'border-primary/30 text-primary'}`}><span className={`h-2 w-2 rounded-full ${connection==='open'?'status-pulse bg-secondary':'bg-primary'}`}/><span className="data-mono text-[9px]">{connection==='open'?'BACKEND + WEBSOCKET CONNECTED':'WEBSOCKET RECONNECTING'}</span></div>}/>
    <ScenarioControls/>
    <section className={`mb-5 border p-4 ${critical?'border-destructive/60 bg-destructive/10':'border-primary/35 bg-primary/[.05]'}`}>
      <div className="grid gap-4 lg:grid-cols-[1fr_auto] lg:items-center"><div className="flex gap-3"><CircleAlert size={20} className={critical?'text-destructive':'text-primary'}/><div><div className="data-mono text-[8px] text-muted-foreground">WHAT IS HAPPENING?</div><h2 className="mt-1 text-[15px] font-semibold">{prediction.crowd_state}{affected?` · ${affected.name}`:''}</h2><p className="mt-2 max-w-3xl text-[11px] leading-relaxed text-muted-foreground">{decision.reason}</p></div></div><div className="grid grid-cols-2 gap-px bg-border sm:grid-cols-4"><Brief label="SAFER EXIT" value={recommended?.name??'NONE'}/><Brief label="ACTION" value={decision.action}/><Brief label="INTERVENTION" value={intervention.status}/><Brief label="TREND" value={trend}/></div></div>
    </section>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Gauge} label="CROWD RISK" value={String(Math.round(prediction.risk))} unit="/ 100" note={prediction.crowd_state} danger={prediction.risk>=75}/><Metric icon={Users} label="PEOPLE IN FIELD" value={String(facility.zones.reduce((sum,zone)=>sum+zone.metrics.people_count,0))} unit="TRACKS" note={prediction.simulated?'SIMULATED':'PROVIDER DATA'}/><Metric icon={ArrowRight} label="RECOMMENDED EXIT" value={recommended?.name??'NONE'} unit="ROUTE" note={decision.exit_ranking.length?`#1 OF ${decision.exit_ranking.length}`:'NO AVAILABLE EXIT'}/><Metric icon={Bot} label="CONTROL MODE" value={snapshot.automatic_control?'AUTOMATIC':'MANUAL'} unit="BACKEND" note={facility.sentinels.every((item)=>item.connected)?'SENTINELS CONNECTED':'UNIT OFFLINE'}/></div>
    <div className="grid gap-5 xl:grid-cols-[1.45fr_1fr]"><Panel title="Live facility map" eyebrow="DYNAMIC ZONES / ROUTES / JUNCTIONS"><MapPanel/></Panel><Panel title="Exit ranking" eyebrow="LOWER SAFETY SCORE IS BETTER"><div className="divide-y divide-border">{decision.exit_ranking.map((item,index)=><div key={item.exit_id} className="flex items-center gap-3 p-4"><span className="data-mono text-[15px] text-primary">#{index+1}</span><div className="min-w-0 flex-1"><div className="text-[11px] font-semibold">{item.name}</div><div className="mt-1 data-mono text-[8px] text-muted-foreground">{item.exit_id}</div></div><span className="data-mono text-[12px] text-secondary">{item.score}</span></div>)}{decision.exit_ranking.length===0&&<div className="p-8 text-center data-mono text-[9px] text-destructive">NO AVAILABLE EXIT</div>}</div></Panel></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_1fr]"><Panel title="Risk trajectory" eyebrow="TIMESTAMPED BACKEND HISTORY" action={<span className={`flex items-center gap-1 data-mono text-[9px] ${trend==='IMPROVING'?'text-secondary':trend==='WORSENING'?'text-destructive':'text-primary'}`}>{trend==='IMPROVING'?<TrendingDown size={13}/>:<TrendingUp size={13}/>} {trend}</span>}><div className="h-[250px] p-3"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><CartesianGrid stroke="#263442" strokeDasharray="2 5" vertical={false}/><XAxis dataKey="time" tick={{fill:'#768493',fontSize:8}} axisLine={false} tickLine={false}/><YAxis domain={[0,100]} tick={{fill:'#768493',fontSize:8}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#17232f',border:'1px solid #334454',fontSize:10}}/><Area type="monotone" dataKey="risk" stroke="#e8aa3d" fill="#e8aa3d22" strokeWidth={2}/>{marker&&<ReferenceLine x={marker} stroke="#41b4b9" strokeDasharray="4 3" label={{value:'INTERVENTION',fill:'#41b4b9',fontSize:8,position:'insideTopRight'}}/>}</AreaChart></ResponsiveContainer></div></Panel><Panel title="Explainability" eyebrow="WHY THIS CLASSIFICATION?"><div className="divide-y divide-border">{prediction.explanations.map((item)=><div key={item.signal} className="p-4"><div className="flex justify-between text-[10px]"><span>{item.signal}</span><span className="data-mono text-primary">{Math.round(item.value)}</span></div><p className="mt-2 text-[9px] leading-relaxed text-muted-foreground">{item.description}</p><div className="mt-2 h-1 bg-muted"><div className="h-full bg-secondary" style={{width:`${Math.min(100,item.contribution*100)}%`}}/></div></div>)}</div></Panel></div>
    <Panel title="Sentinel action stack" eyebrow="ALL CONFIGURED STATIONARY UNITS" className="mt-5"><div className="grid gap-px bg-border lg:grid-cols-2">{facility.sentinels.map((sentinel)=><div key={sentinel.id} className="bg-card p-4"><div className="flex items-center justify-between"><div><div className="text-[12px] font-semibold">{sentinel.name}</div><div className="mt-1 data-mono text-[8px] text-muted-foreground">{sentinel.device_id} · {sentinel.connected?'CONNECTED':'DISCONNECTED'}</div></div><Activity size={16} className={sentinel.connected?'text-secondary':'text-destructive'}/></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><State label="ARM" value={sentinel.hardware_state.arm_state}/><State label="DISPLAY" value={sentinel.hardware_state.display_message}/><State label="AUDIO" value={`${sentinel.hardware_state.audio} · ${sentinel.hardware_state.audio_state}`}/>{Object.entries(sentinel.hardware_state.led_routes).map(([exitId,value])=><State key={exitId} label={`${facility.exits.find((exit)=>exit.id===exitId)?.name??exitId} LED ROUTE`} value={value}/>)}</div></div>)}{facility.sentinels.length===0&&<div className="bg-card p-8 text-center data-mono text-[9px] text-muted-foreground">NO SENTINEL CONFIGURED</div>}</div></Panel>
    <div className="mt-5 flex flex-wrap items-center gap-3 border border-border p-3"><ShieldCheck size={15} className="text-secondary"/><p className="min-w-60 flex-1 text-[10px] text-muted-foreground">Automatic control is enforced by the backend decision and hardware services. The browser never addresses ESP32 directly.</p><button onClick={()=>void toggleAutomatic()} className="border border-primary/40 px-3 py-2 data-mono text-[9px] text-primary">{snapshot.automatic_control?'SWITCH TO MANUAL':'ENABLE AUTOMATIC'}</button></div>
  </div>;
}
function Brief({label,value}:{label:string;value:string}){return <div className="min-w-28 bg-card p-3"><div className="data-mono text-[7px] text-muted-foreground">{label}</div><div className="mt-2 data-mono text-[9px] text-foreground">{value}</div></div>}
function Metric({icon:Icon,label,value,unit,note,danger=false}:{icon:typeof Gauge;label:string;value:string;unit:string;note:string;danger?:boolean}){return <div className="panel p-4"><div className="flex justify-between"><span className="data-mono text-[8px] text-muted-foreground">{label}</span><Icon size={15} className={danger?'text-destructive':'text-secondary'}/></div><div className={`mt-3 data-mono text-[25px] ${danger?'text-destructive':'text-primary'}`}>{value} <span className="text-[8px] text-muted-foreground">{unit}</span></div><div className="mt-2 data-mono text-[8px] text-muted-foreground">{note}</div></div>}
function State({label,value}:{label:string;value:string}){return <div className="border border-border bg-muted/20 p-3"><div className="data-mono text-[7px] text-muted-foreground">{label}</div><div className="mt-2 data-mono text-[9px] text-foreground">{value}</div></div>}
